require "modules.classic"
require "src.controllers.inputs"
require "src.motors.enemyManager"
require "src.motors.prints"
require "src.prefabs.prefab"
require "src.prefabs.crosshair"
require "src.utils.math"
require "src.entities.player"